name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    # Set up a specific Node.js version
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Install and cache vcpkg
    - name: Setup vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ./vcpkg
          !./vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/*.cpp', '**/*.h') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    # Install dependencies
    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install

    # Configure project with CMake and set toolchain file
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build

    # Optionally run tests or other commands
    - name: Execute tests
      run: |
        cmake --build build --target test
